import type { Metadata } from "next";
import { Figtree, Geist, Geist_Mono, Josefin_Sans, Montserrat } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const josefin = Josefin_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"], // Select the weights you need
  variable: "--font-josefin", // This defines a CSS variable we use in Tailwind
  display: "swap",
});

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  // Optional: specify weights if you don't want the entire variable font
  weight: ['400', '700'], 
  variable: '--font-montserrat', // This creates a CSS variable
});


const figtree = Figtree({
  subsets: ['latin'],
  variable: '--font-figtree',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth js" suppressHydrationWarning>
<head>
  <script
    type="application/ld+json"
    dangerouslySetInnerHTML={{
      __html: JSON.stringify({
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": "Uptimise IT",
        "url": "https://uptimise.com",
        "logo": "https://uptimise.com/logo.png",
        "description": "Uptimise IT is an AI-native product engineering company helping startups and enterprises build scalable digital platforms using modern technologies and AI-assisted development workflows.",
        "founder": {
          "@type": "Person",
          "name": "Saurabh Sharma"
        },
        "sameAs": [
          "https://www.linkedin.com/company/uptimise",
          "https://twitter.com/uptimise",
          "https://github.com/uptimise"
        ],
        "contactPoint": {
          "@type": "ContactPoint",
          "contactType": "customer support",
          "email": "contact@uptimise.com"
        }
      })
    }}
  />
</head>
      <body
        className={`${josefin.variable} antialiased ${montserrat.variable} ${figtree.variable}`}
      >
    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
      <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
